//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN


#include "../common/common.glsl"
#include "../common/math_constants.glsl"
#include "pcs/pcs_raygen.glsl"
#include "ris.glsl"

layout(set = 0, binding = 4, rgba32f) uniform image2D outputImage;

layout(location = 0) rayPayloadEXT HitPayload payload;


//  all zero normals are invalid
bool isGeometryValid(vec3 normal){
    float epsilon = 1e-6;
    return any(greaterThan(abs(normal),vec3(epsilon)));
}

vec3 reconstructPositionWS(vec2 uv, float depth){
    uv.y = 1.0 - uv.y;
    vec2 ndcXY = uv * 2.0 - 1.0; // move from [0, 1] to [-1, 1] range   
    vec4 camRay = cameraUBO.matInvVP * vec4(ndcXY,depth,1);
    return camRay.xyz / camRay.w;
}

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    //  if there's no geometry, draw the sky into the output image and early exit (no rays traced)
    //  (in this case, the sky texture is already pre-rendered in the G buffer shading target texture) 
    vec4 normalRoughness = texture(textures[pcs.normalMapHandle], uv);
    if (!isGeometryValid(normalRoughness.xyz)){
        vec3 sky = texture(textures[pcs.targetHandle],uv).xyz;
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(sky, 1.0));
        return;
    }

    // early exit on emissive materials -- write emission directly into output image
    Material mat = materialUBO.materials[uint(texture(utextures[pcs.materialMapHandle],uv).r)];
    if (any(notEqual(mat.emissionMetallic.rgb,vec3(0.0)))){
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(mat.emissionMetallic.rgb, 1.0));
        return;
    }

    ShadeParams params;

    //  load the rest of the textures
    params.normal = normalize(normalRoughness.xyz);
    params.roughness = normalRoughness.w;

    vec4 albedoMetallic = texture(textures[pcs.albedoMapHandle], uv);
    params.albedo = albedoMetallic.rgb;
    params.metallic = albedoMetallic.w;

    float depth = texture(textures[pcs.depthMapHandle], uv).x;

    // initial ray and shading parameters
    // at first, take them from the G buffer fill step, then reuse them when bouncing rays  
    vec3 posWS = reconstructPositionWS(uv,depth);
    vec3 rayDir = normalize(posWS - cameraUBO.posWS);

    if (dot(-rayDir,params.normal) < 0.0)
        params.normal *= -1.0f;

    vec3 brdf = vec3(0.0);
    vec4 sampled = sampleMaterial(rayDir, params, mat.materialType, seed, brdf);
    vec3 direction = sampled.xyz;
    float pdf = sampled.w;

    float cosThetaI = mat.materialType == MAT_MIRROR ? 1.0 : max(dot(direction,params.normal),0.0);

    vec3 weightFactor = vec3(0.0);
    if (pdf > 0.0f)
        weightFactor = brdf * cosThetaI / pdf;

    float tMin = 0.001f;
    float tMax = 10000.0f;

    vec3 radiance = vec3(0.0);
    vec3 weight = vec3(1.0);

    vec3 directContribution = vec3(0.0);

    if (mat.materialType != MAT_MIRROR){
        directContribution = bool(pcs.ris & (1 << 31))
            ? calculateDirectRIS(params,posWS,rayDir,mat.materialType,seed)  
            : calculateDirect(params,posWS,rayDir,mat.materialType,seed);
    }

    bool lastWasMirror = mat.materialType == 1;
    for (uint depth = 0; depth < pcs.maxRecursionDepth; depth++){
        
        resetPayload(payload);
        payload.seed = seed;
        traceRayEXT(
            topLevelAS,
            gl_RayFlagsOpaqueEXT,
            0xff, // cullMask
            0,    // sbtRecordOffset
            0,    // sbtRecordStride
            0,    // missIndex
            posWS + tMin *  params.normal,
            tMin,
            direction,
            tMax,
            0     // payloadLocation
        );

        radiance += weight * directContribution;


        // hitting a light from a material that was not a mirror previously ends the path (emissive surfaces handled in direct lighting calculation)
        // break before integrating radiance (that would result in double counting)
        if(hitLight(payload) && !lastWasMirror)
            break;

        weight *= weightFactor;
        radiance += weight * payload.hitEmission; 

        // break if no hit (after integrating radiance from environment map)
        if (!payload.hit)
            break;
    
        ///////////////////////////////////////////////////////////
        // russian roulette termination
        if (depth > 4) {
            float survivalProb = max(weight.x,max(weight.y,weight.z));
            survivalProb = max(survivalProb, 0.15);
            float rnd = rand(seed);
            if (rnd > survivalProb) break;
            weight /= survivalProb;
        }
        ///////////////////////////////////////////////////////////

        posWS = payload.hitPosition;
        direction = payload.nextSample.xyz;
        pdf = payload.nextSample.w;
        weightFactor = payload.weightFactor;
        seed = payload.seed;
        lastWasMirror = payload.mirror;
        directContribution = payload.directContribution;
        params.normal = payload.hitNormal;

    }

    if (pcs.accumulate == 1) {
        vec3 oldRadiance = imageLoad(outputImage, ivec2(gl_LaunchIDEXT.xy)).xyz;
        radiance = mix(oldRadiance,radiance, 1.0f / float(pcs.frameCtr + 1));
    }

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(radiance, 1.0));
}

#undef RAYGEN
