//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable

#include "../common/common.glsl"
#include "../common/math_constants.glsl"
#include "pcs/pcs_raygen.glsl"
#include "raycommon.glsl"
#include "sampling.glsl"
#include "structs/payload.glsl"

layout(set = 0, binding = 4, rgba32f) uniform image2D outputImage;

layout(location = 0) rayPayloadEXT HitPayload payload;


//  all zero normals are invalid
bool isGeometryValid(vec3 normal){
    float epsilon = 1e-6;
    return any(greaterThan(abs(normal),vec3(epsilon)));
}

vec3 reconstructPositionWS(vec2 uv, float depth){
    uv.y = 1.0 - uv.y;
    vec2 ndcXY = uv * 2.0 - 1.0; // move from [0, 1] to [-1, 1] range   
    vec4 camRay = cameraUBO.matInvVP * vec4(ndcXY,depth,1);
    return camRay.xyz / camRay.w;
}

float linearizeDepth(float depth, float zNear, float zFar){
    return zNear * zFar / (zFar + depth * (zNear - zFar));
}

CDFElement sampleLight(float rnd){
    uint left = 0;
    uint right = emissiveCDF.size - 1;

    while (left < right){
        uint mid = left + (right - left) / 2;

        if (rnd < emissiveCDF.cdf[mid].cdfVal)
            right = mid;
        else
            left = mid + 1;
    }
    return emissiveCDF.cdf[left];
}

void main() { 
    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    //  if there's no geometry, draw the sky into the output image and early exit (no rays traced)
    //  (in this case, the sky texture is already pre-rendered in the G buffer shading target texture) 
    vec4 normalShininess = texture(textures[pcs.normalMapHandle], uv);
    if (!isGeometryValid(normalShininess.xyz)){
        vec3 sky = texture(textures[pcs.targetHandle],uv).xyz;
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(sky, 1.0));
        return;
    }

    // early exit on emissive materials -- write emission directly into output image
    Material mat = materialUBO.materials[uint(texture(utextures[pcs.materialMapHandle],uv).r)];
    if (any(notEqual(mat.emission,vec3(0.0)))){
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(mat.emission, 1.0));
        return;
    }

    //  load the rest of the textures
    vec3 normal = normalize(normalShininess.xyz);
    float shininess = normalShininess.w;
    vec3 albedo = texture(textures[pcs.albedoMapHandle], uv).xyz;
    float depth = texture(textures[pcs.depthMapHandle], uv).x;

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    // initialize ray
    // initial origin is the world space position of first hit (first hit is rasterized by G buffer fill step)
    // initial direction is sampled according to material at ray origin
    vec3 posWS = reconstructPositionWS(uv,depth);
    vec4 sampled = sampleHemisphereCosineWeighted(normal,seed);
    vec3 direction = sampled.xyz;
    float pdf = sampled.w;

    // this can be evaluated before tracing any rays, since everything except hitEmission (L_i) is known in advance from the g buffer
    // at least for the first hit 
    float cosThetaI = max(dot(direction,normal),0.0);
    vec3 brdf = albedo / PI;

    float tMin = 0.001f;
    float tMax = 10000.0f;

    vec3 radiance = vec3(0.0);
    vec3 weight = vec3(1.0);
    resetPayload(payload);
    for (uint depth = 0; depth < pcs.maxRecursionDepth; depth++){
        
        resetPayload(payload);
        traceRayEXT(
            topLevelAS,
            gl_RayFlagsOpaqueEXT,
            0xff, // cullMask
            0,    // sbtRecordOffset
            0,    // sbtRecordStride
            0,    // missIndex
            posWS + normal * tMin,
            tMin,
            direction,
            tMax,
            0     // payloadLocation
        );

       
        weight *= brdf * max(dot(direction,normal),0.0) / pdf;
        radiance += weight * payload.hitEmission;

        posWS = payload.hitPosition;
        normal = payload.hitNormal;
        sampled = sampleHemisphereCosineWeighted(normal,seed);
        direction = sampled.xyz;
        pdf = sampled.w;

        brdf = payload.hitBrdf;

        cosThetaI = max(dot(direction,normal),0.0);

        if(!payload.hit || any(greaterThan(payload.hitEmission,vec3(0.0)))) break;
    }

    if (pcs.accumulate == 1){
        vec3 oldRadiance = imageLoad(outputImage, ivec2(gl_LaunchIDEXT.xy)).xyz;
        radiance = mix(oldRadiance,radiance, 1.0f / float(pcs.frameCtr + 1));
    }

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(radiance, 1.0));
    //imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(emissiveBuffer.tris[0].v0eR.xyz + emissiveCDF.cdf[0].cdfVal, 1.0 * huh));
}