//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#include "../common/common.glsl"
#include "../common/math_constants.glsl"
#include "pcs/pcs_raygen.glsl"
#include "raycommon.glsl"
#include "mis.glsl"

layout(set = 0, binding = 4, rgba32f) uniform image2D outputImage;

layout(location = 0) rayPayloadEXT HitPayload payload;


//  all zero normals are invalid
bool isGeometryValid(vec3 normal){
    float epsilon = 1e-6;
    return any(greaterThan(abs(normal),vec3(epsilon)));
}

vec3 reconstructPositionWS(vec2 uv, float depth){
    uv.y = 1.0 - uv.y;
    vec2 ndcXY = uv * 2.0 - 1.0; // move from [0, 1] to [-1, 1] range   
    vec4 camRay = cameraUBO.matInvVP * vec4(ndcXY,depth,1);
    return camRay.xyz / camRay.w;
}

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    //  if there's no geometry, draw the sky into the output image and early exit (no rays traced)
    //  (in this case, the sky texture is already pre-rendered in the G buffer shading target texture) 
    vec4 normalShininess = texture(textures[pcs.normalMapHandle], uv);
    if (!isGeometryValid(normalShininess.xyz)){
        vec3 sky = texture(textures[pcs.targetHandle],uv).xyz;
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(sky, 1.0));
        return;
    }

    // early exit on emissive materials -- write emission directly into output image
    Material mat = materialUBO.materials[uint(texture(utextures[pcs.materialMapHandle],uv).r)];
    if (any(notEqual(mat.emission,vec3(0.0)))){
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(mat.emission, 1.0));
        return;
    }

    //  load the rest of the textures
    vec3 normal = normalize(normalShininess.xyz);
    float shininess = normalShininess.w;
    vec3 albedo = texture(textures[pcs.albedoMapHandle], uv).xyz;
    float depth = texture(textures[pcs.depthMapHandle], uv).x;

    // initial ray and shading parameters
    // at first, take them from the G buffer fill step, then reuse them when bouncing rays  
    vec3 posWS = reconstructPositionWS(uv,depth);
    vec3 rayDir = normalize(posWS - cameraUBO.posWS);

    vec4 sampled = sampleMaterial(normal, rayDir, mat.materialType, seed);
    
    vec3 direction = sampled.xyz;
    float pdf = sampled.w;

    float cosThetaI = mat.materialType == 1 ? 1.0 : max(dot(direction,normal),0.0);
    vec3 brdf = mat.materialType == 1 ? albedo : albedo * INVPI;

    vec3 weightFactor = brdf * cosThetaI / pdf;

    float tMin = 0.001f;
    float tMax = 10000.0f;

    vec3 radiance = vec3(0.0);
    vec3 weight = vec3(1.0);

    vec3 directContribution = mat.materialType == 1 ? vec3(0.0) : calculateDirect(albedo,posWS,normal,seed);

    radiance += weight * directContribution;
    
    float p_survive = 1.0;

    bool lastWasMirror = mat.materialType == 1;
    for (uint depth = 0; depth < pcs.maxRecursionDepth - 1; depth++){


        resetPayload(payload);
        payload.seed = seed;
        traceRayEXT(
            topLevelAS,
            gl_RayFlagsOpaqueEXT,
            0xff, // cullMask
            0,    // sbtRecordOffset
            0,    // sbtRecordStride
            0,    // missIndex
            posWS + tMin * normal,
            tMin,
            direction,
            tMax,
            0     // payloadLocation
        );

        // hitting a light from a material that was not a mirror previously ends the path (emissive surfaces handled in direct lighting calculation)
        if(payload.hit && hitLight(payload) && !lastWasMirror)
            break;
        // missing from a material that was not a mirror previously ends the path (env map is handled in direct lighting calculation)
        if (!payload.hit && !lastWasMirror)
            break;

        weight *= weightFactor;
        radiance += weight * payload.hitEmission;  
        radiance += weight * payload.directContribution;

        if (!payload.hit)
            break;


        ///////////////////////////////////////////////////////////
        // russian roulette termination
        if (depth > 4) {
            float survivalProb = max(weight.x,max(weight.y,weight.z));
            survivalProb = max(survivalProb, 0.15);
            float rnd = rand(seed);
            if (rnd > survivalProb) break;
            weight /= survivalProb;
        }
        ///////////////////////////////////////////////////////////

        posWS = payload.hitPosition;
        direction = payload.nextSample.xyz;
        pdf = payload.nextSample.w;
        directContribution = payload.directContribution;
        weightFactor = payload.weightFactor;
        seed = payload.seed;
        lastWasMirror = payload.mirror;
        normal = payload.hitNormal;

    }

    if (pcs.accumulate == 1) {
        vec3 oldRadiance = imageLoad(outputImage, ivec2(gl_LaunchIDEXT.xy)).xyz;
        radiance = mix(oldRadiance,radiance, 1.0f / float(pcs.frameCtr + 1));
    }

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(radiance, 1.0));
}