//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN

#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../ris.glsl"

layout(set = 0, binding = 4, rgba32f) uniform image2D outputImage;



void main() { 
    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    vec4 normalRoughness = texture(textures[pcs.normalMapHandle], uv);
    Material mat = materialUBO.materials[uint(texture(utextures[pcs.materialMapHandle],uv).r)];

    // early exit on emissive materials or invalid normals
    if (any(notEqual(mat.emissionMetallic.rgb,vec3(0.0))) || !isGeometryValid(normalRoughness.xyz))
        return;

    ShadeParams params;

    //  load the rest of the textures
    params.normal = normalize(normalRoughness.xyz);
    params.roughness = normalRoughness.w;

    vec4 albedoMetallic = texture(textures[pcs.albedoMapHandle], uv);
    params.albedo = albedoMetallic.rgb;
    params.metallic = albedoMetallic.w;

    float depth = texture(textures[pcs.depthMapHandle], uv).x;

    // initial ray and shading parameters
    // at first, take them from the G buffer fill step, then reuse them when bouncing rays  
    vec3 posWS = reconstructPositionWS(uv,depth);
    vec3 rayDir = normalize(posWS - cameraUBO.posWS);

    if (dot(-rayDir,params.normal) < 0.0)
        params.normal *= -1.0f;

    Reservoir r = makeEmptyReservoir();

    if (mat.materialType != MAT_MIRROR)
        r = resampleInitialCandidates(params,posWS,rayDir,mat.materialType, seed);  



    uint bufferWritePosition = flatten2DCoord(gl_LaunchIDEXT.xy, uvec2(imageSize));
    uint bufferWriteIndex = getBufferWriteIndex(); 
    reservoirBuffers[bufferWriteIndex].reservoirs[bufferWritePosition] = r;
}

#undef RAYGEN
