//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN
#define BRDF_HIT_START_OFFSET 3

#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../ris.glsl"

layout(set = 0, binding = 4, rgba32f) uniform image2D outputImage;


uint flatten2DCoord(uvec2 coord){
    uvec2 size = imageSize(outputImage);
    return size.x * coord.y + coord.x;
}

//  all zero normals are invalid
bool isGeometryValid(vec3 normal){
    float epsilon = 1e-6;
    return any(greaterThan(abs(normal),vec3(epsilon)));
}

vec3 reconstructPositionWS(vec2 uv, float depth){
    uv.y = 1.0 - uv.y;
    vec2 ndcXY = uv * 2.0 - 1.0; // move from [0, 1] to [-1, 1] range   
    vec4 camRay = cameraUBO.matInvVP * vec4(ndcXY,depth,1);
    return camRay.xyz / camRay.w;
}

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    //  if there's no geometry, draw the sky into the output image and early exit (no rays traced)
    //  (in this case, the sky texture is already pre-rendered in the G buffer shading target texture) 
    vec4 normalRoughness = texture(textures[pcs.normalMapHandle], uv);
    if (!isGeometryValid(normalRoughness.xyz)){
        vec3 sky = texture(textures[pcs.targetHandle],uv).xyz;
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(sky, 1.0));
        return;
    }

    // early exit on emissive materials -- write emission directly into output image
    Material mat = materialUBO.materials[uint(texture(utextures[pcs.materialMapHandle],uv).r)];
    if (any(notEqual(mat.emissionMetallic.rgb,vec3(0.0)))){
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(mat.emissionMetallic.rgb, 1.0));
        return;
    }

    ShadeParams params;

    //  load the rest of the textures
    params.normal = normalize(normalRoughness.xyz);
    params.roughness = normalRoughness.w;

    vec4 albedoMetallic = texture(textures[pcs.albedoMapHandle], uv);
    params.albedo = albedoMetallic.rgb;
    params.metallic = albedoMetallic.w;

    float depth = texture(textures[pcs.depthMapHandle], uv).x;

    // initial ray and shading parameters
    // at first, take them from the G buffer fill step, then reuse them when bouncing rays  
    vec3 posWS = reconstructPositionWS(uv,depth);
    vec3 rayDir = normalize(posWS - cameraUBO.posWS);

    if (dot(-rayDir,params.normal) < 0.0)
        params.normal *= -1.0f;

    vec3 radiance = vec3(0.0);

    vec3 directContribution = vec3(0.0);

    Reservoir r;

    if (mat.materialType != MAT_MIRROR)
        directContribution = calculateDirectRIS(params,posWS,rayDir,mat.materialType, seed, r);  

    radiance = directContribution;
    
    if (pcs.accumulate == 1) {
        vec3 oldRadiance = imageLoad(outputImage, ivec2(gl_LaunchIDEXT.xy)).xyz;
        radiance = mix(oldRadiance,radiance, 1.0f / float(pcs.frameCtr + 1));
    }
    reservoirBuffers[0].reservoirs[flatten2DCoord(gl_LaunchIDEXT.xy)] = r;
    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(radiance, 1.0));
}

#undef BRDF_HIT_START_OFFSET
#undef RAYGEN
