//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN

#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../ris.glsl"

void main() { 
    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    ShadeParams params;
    vec3 posWS;
    vec3 rayDir;
    Material mat;

    if (!unpackFirstHitRestir(uv,params,posWS,rayDir, mat))
        return;

    Reservoir r = makeEmptyReservoir();

    if (mat.materialType != MAT_MIRROR)
        r = resampleInitialCandidates(params,posWS,rayDir,mat.materialType, seed);  

    uint bufferWritePosition = flatten2DCoord(gl_LaunchIDEXT.xy, uvec2(imageSize));
    uint bufferWriteIndex = getBufferWriteIndex(); 
    reservoirBuffers[bufferWriteIndex].reservoirs[bufferWritePosition] = r;
}

#undef RAYGEN
