//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN

#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../ris.glsl"

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    ShadeParams params;
    vec3 posWS;
    vec3 rayDir;
    Material mat;

    if (!unpackFirstHit(uv,params,posWS,rayDir, mat))
        return;

    // get the reservoir to read from
    uint bufferReadPosition = flatten2DCoord(gl_LaunchIDEXT.xy, uvec2(imageSize));
    uint bufferReadIndex = getBufferReadIndex(); 
    Reservoir r = reservoirBuffers[bufferReadIndex].reservoirs[bufferReadPosition];

    // save it to history, so that it can be used during the next temporal pass 
    reservoirBuffers[HISTORY_RESERVOIR_BUFFER_INDEX].reservoirs[bufferReadPosition] = r;
    
    vec3 directContribution = vec3(0.0);

    r.wSum = sanitize(r.wSum);
    vec3 F = vec3(0.0);
    float p_hat = evalPhat(r.bestSample, params, posWS, rayDir, mat.materialType, F);

    directContribution = F * r.W;
    
    vec3 radiance = sanitize(directContribution);
    
    if (pcs.accumulate == 1) {
        vec3 oldRadiance = imageLoad(outputImage, ivec2(gl_LaunchIDEXT.xy)).xyz;
        radiance = mix(oldRadiance,radiance, 1.0f / float(pcs.frameCtr + 1));
    }

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(radiance, 1.0));
}


#undef RAYGEN
