//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN


#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../ris.glsl"

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    ShadeParams params;
    vec3 posWS;
    vec3 rayDir;
    Material mat;

    if (!unpackFirstHitRestir(uv,params,posWS,rayDir, mat))
        return;

    uint neighborCount = getNeighborCount();

    uvec2 neighborPixelCoords[32];
    ShadeParams neighborShadeParams[32];
    vec3 neighborPosWSs[32];
    vec3 neighborRayDirs[32];
    Material neighborMaterials[32];
    
    // preinitialize current pixel
    neighborPixelCoords[0] = uvec2(imageCoord);
    neighborShadeParams[0] = params;
    neighborPosWSs[0] = posWS;
    neighborRayDirs[0] = rayDir;
    neighborMaterials[0] = mat;

    // accepted neighbor count
    uint M = 1;

    // gather neighbor coords
    // start at index 1 since index 0 is occupied by this pixel's sample 
    for (uint i = 0; i < neighborCount; ++i){
        vec2 sampledDisk = sampleDiskUniform(100.0f, seed);
        vec2 neighborCoord = clamp(sampledDisk + imageCoord, vec2(0.0f), imageSize - 1);
        vec2 neighborUv = neighborCoord / imageSize;
        uvec2 neighborPixelCoord = uvec2(neighborCoord);
        
        ShadeParams neighborParams;
        vec3 neighborPosWS;
        vec3 neighborRayDir;
        Material neighborMat;

        if (!unpackFirstHitRestir(neighborUv, neighborParams, neighborPosWS, neighborRayDir, neighborMat))
            continue;

        neighborPixelCoords[M] = neighborPixelCoord;
        neighborShadeParams[M] = neighborParams;
        neighborPosWSs[M] = neighborPosWS;
        neighborRayDirs[M] = neighborRayDir;
        neighborMaterials[M] = neighborMat;
        M += 1;
    }

    uint bufferReadIndex = getBufferReadIndex(); 
    uint bufferWriteIndex = getBufferWriteIndex(); 

    Reservoir outReservoir = makeEmptyReservoir();

    float misWeight = M > 0 ? 1.0f / float(M) : 0.0f;
    for (uint i = 0; i < M; ++i) {

        uint bufferReadPosition = flatten2DCoord(neighborPixelCoords[i], uvec2(imageSize));
        Reservoir reservoir_i = reservoirBuffers[bufferReadIndex].reservoirs[bufferReadPosition];
        CandidateSample sample_i = reservoir_i.bestSample;

        float p_hat = evalPhat(sample_i, params, posWS, rayDir, mat.materialType);
        float w = misWeight * p_hat * reservoir_i.W;
        addSample(outReservoir, sample_i, w, seed);
    }

    outReservoir.wSum = sanitize(outReservoir.wSum);

    float p_hat = evalPhat(outReservoir.bestSample, params, posWS, rayDir, mat.materialType);
    outReservoir.W = p_hat > 0.0f ? 1.0f / p_hat * outReservoir.wSum : 0.0f;    

    uint bufferWritePosition = flatten2DCoord(gl_LaunchIDEXT.xy, uvec2(imageSize)); 
    reservoirBuffers[bufferWriteIndex].reservoirs[bufferWritePosition] = outReservoir;
}

#undef RAYGEN
