//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN


#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../ris.glsl"

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    ShadeParams params;
    vec3 posWS;
    vec3 rayDir;
    Material mat;

    if (!unpackFirstHitRestir(uv,params,posWS,rayDir, mat))
        return;

    uint neighborCount = getNeighborCount();

    uvec2 neighborPixelCoords[32];
    ShadeParams neighborShadeParams[32];
    vec3 neighborPosWSs[32];
    vec3 neighborRayDirs[32];
    Material neighborMaterials[32];
    
    // preinitialize current pixel
    neighborPixelCoords[0] = uvec2(imageCoord);
    neighborShadeParams[0] = params;
    neighborPosWSs[0] = posWS;
    neighborRayDirs[0] = rayDir;
    neighborMaterials[0] = mat;

    // accepted neighbor count
    uint M = 1;

    // gather neighbor coords
    // start at index 1 since index 0 is occupied by this pixel's sample 
    for (uint i = 0; i < neighborCount; ++i){
        vec2 sampledDisk = ivec2(sampleDiskUniform(100.0f, seed));

        ivec2 iNeighborCoord = ivec2(floor(sampledDisk + imageCoord));
        iNeighborCoord = clamp(iNeighborCoord, ivec2(0), ivec2(imageSize) - 1);

        // sample pixel centers
        vec2 neighborUv = (vec2(iNeighborCoord) + 0.5) / imageSize;
        
        ShadeParams neighborParams;
        vec3 neighborPosWS;
        vec3 neighborRayDir;
        Material neighborMat;

        if (!unpackFirstHitRestir(neighborUv, neighborParams, neighborPosWS, neighborRayDir, neighborMat))
            continue;

        neighborPixelCoords[M] = uvec2(iNeighborCoord);
        neighborShadeParams[M] = neighborParams;
        neighborPosWSs[M] = neighborPosWS;
        neighborRayDirs[M] = neighborRayDir;
        neighborMaterials[M] = neighborMat;
        M += 1;
    }

    uint bufferReadIndex = getBufferReadIndex(); 
    uint bufferWriteIndex = getBufferWriteIndex(); 

    Reservoir outReservoir = makeEmptyReservoir();

    float misWeight = M > 0 ? 1.0f / float(M) : 0.0f;
    for (uint i = 0; i < M; ++i) {

        uint bufferReadPosition = flatten2DCoord(neighborPixelCoords[i], uvec2(imageSize));
        Reservoir reservoir_i = reservoirBuffers[bufferReadIndex].reservoirs[bufferReadPosition];
        CandidateSample sample_i = reservoir_i.bestSample;

        bool positionSample = false;
        float jacobian = 1.0f;
        float _ = unpackMisWeight(sample_i.misWeight,positionSample);

        // the jacobian determinant needs to be calculated to scale the solid angle weight as if it came from this pixel
        // GRIS paper
        // x denotes the current pixel
        // y denotes the neighbor pixel (and its sample)
        // https://graphics.cs.utah.edu/research/projects/gris/sig22_GRIS.pdf
        if (positionSample){

            vec3 x_surf_to_y_hit = sample_i.omega_i - posWS;
            vec3 x_surf_to_y_hit_dir = normalize(x_surf_to_y_hit);
            float x_surf_to_y_dist = length(x_surf_to_y_hit);
            float x_surf_to_y_dist_sqr = x_surf_to_y_dist * x_surf_to_y_dist;
            
            vec3 y_surf_to_y_hit = sample_i.omega_i - neighborPosWSs[i];
            vec3 y_surf_to_y_hit_dir = normalize(y_surf_to_y_hit);
            float y_surf_to_y_dist = length(y_surf_to_y_hit);
            float y_surf_to_y_dist_sqr = y_surf_to_y_dist * y_surf_to_y_dist;

            float cos_theta_x = max(dot(-x_surf_to_y_hit_dir, sample_i.normal), 0.0f);
            float cos_theta_y = max(dot(-y_surf_to_y_hit_dir, sample_i.normal), 0.0f);

            float dist_term = y_surf_to_y_dist_sqr / x_surf_to_y_dist_sqr;
            float cos_term = cos_theta_x / cos_theta_y;

            jacobian = sanitize(dist_term * cos_term);
        }

        float p_hat = evalPhatVis(sample_i, params, posWS, rayDir, mat.materialType);
        float w = misWeight * p_hat * reservoir_i.W * jacobian;
        addSample(outReservoir, sample_i, w, seed);
    }

    outReservoir.wSum = sanitize(outReservoir.wSum);

    float p_hat = evalPhat(outReservoir.bestSample, params, posWS, rayDir, mat.materialType);
    outReservoir.W = p_hat > 0.0f ? 1.0f / p_hat * outReservoir.wSum : 0.0f;    

    uint bufferWritePosition = flatten2DCoord(gl_LaunchIDEXT.xy, uvec2(imageSize)); 
    reservoirBuffers[bufferWriteIndex].reservoirs[bufferWritePosition] = outReservoir;
}

#undef RAYGEN
