//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN

#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../ris.glsl"

uvec2 neighborPixelCoords[32];
ShadeParams neighborShadeParams[32];
vec3 neighborPosWSs[32];
vec3 neighborRayDirs[32];
Material neighborMaterials[32];

// total possible neighbor count, set via UI
uint neighborCount;

// accepted neighbor count; set to 1 as default, since the pixel's reservoir should already contain a valid sample from the candidate selection pass
uint M = 1;
float rcpM;

// this pixel's information
ShadeParams params;
vec3 posWS;
vec3 rayDir;
Material mat;



// GRIS paper (https://graphics.cs.utah.edu/research/projects/gris/sig22_GRIS.pdf)
// x denotes the current pixel
// y denotes the neighbor pixel (and its sample sample_i)
// determinant of the jacobian equals the ratio of geometry terms for sample sample_i calculated for both origin points (world space position of this and neighbor pixels) 
float calculateJacobian(CandidateSample sample_i, vec3 posWS, vec3 neighborPos){

    vec3 x_surf_to_y_hit = sample_i.omega_i - posWS;
    vec3 x_surf_to_y_hit_dir = normalize(x_surf_to_y_hit);
    float x_surf_to_y_dist = length(x_surf_to_y_hit);
    float x_surf_to_y_dist_sqr = x_surf_to_y_dist * x_surf_to_y_dist;
    
    vec3 y_surf_to_y_hit = sample_i.omega_i - neighborPos;
    vec3 y_surf_to_y_hit_dir = normalize(y_surf_to_y_hit);
    float y_surf_to_y_dist = length(y_surf_to_y_hit);
    float y_surf_to_y_dist_sqr = y_surf_to_y_dist * y_surf_to_y_dist;

    float cos_theta_x = max(dot(-x_surf_to_y_hit_dir, sample_i.normal), 0.0f);
    float cos_theta_y = max(dot(-y_surf_to_y_hit_dir, sample_i.normal), 0.0f);

    float dist_term = y_surf_to_y_dist_sqr / x_surf_to_y_dist_sqr;
    float cos_term = cos_theta_x / cos_theta_y;

    float jacobian = sanitize(dist_term * cos_term);
    return jacobian;
}

float calculatePairwiseMIS(uint i, CandidateSample sample_i, float p_hat_c){

    float misWeight = 0.0f;

    float p_hat_c_div = p_hat_c / (float(M) - 1);

    // PAIRWISE MIS CALCULATION
    // index i = 0 always contains the canonical sample (this pixel's sample)
    if (i == 0){
        float sum = 0.0f;

        for (uint j = 1; j < M; j++){

            float p_hat_j = evalPhatVis(sample_i, neighborShadeParams[j], neighborPosWSs[j], rayDir, neighborMaterials[j].materialType);

            sum += sanitize(p_hat_c_div / (p_hat_j + p_hat_c_div));
        }
        misWeight = rcpM * (1.0f + sum);
    }
    else{
        float p_hat_i = evalPhatVis(sample_i, neighborShadeParams[i], neighborPosWSs[i], rayDir, neighborMaterials[i].materialType);
        misWeight = rcpM * (p_hat_i) / (p_hat_i + p_hat_c_div); 
    }

    return sanitize(misWeight);
}

void gatherNeighbors(vec2 imageCoord, vec2 imageSize, inout uint seed){
    // gather neighbor coords 
    for (uint i = 0; i < neighborCount; ++i){

        // sample disk to retrieve neighbor pixel coord
        vec2 sampledDisk = sampleDiskUniform(pcs.neighborSearchRadius, seed);

        ivec2 iNeighborCoord = ivec2(floor(sampledDisk + imageCoord));
        iNeighborCoord = clamp(iNeighborCoord, ivec2(0), ivec2(imageSize) - 1);

        // sample pixel centers
        vec2 neighborUv = (vec2(iNeighborCoord) + 0.5) / imageSize;
        
        ShadeParams neighborParams;
        vec3 neighborPosWS;
        vec3 neighborRayDir;
        Material neighborMat;

        if (!unpackFirstHitRestir(neighborUv, neighborParams, neighborPosWS, neighborRayDir, neighborMat))
            continue;

        neighborPixelCoords[M] = uvec2(iNeighborCoord);
        neighborShadeParams[M] = neighborParams;
        neighborPosWSs[M] = neighborPosWS;
        neighborRayDirs[M] = neighborRayDir;
        neighborMaterials[M] = neighborMat;
        M += 1;
    }
    rcpM = 1.0 / float(M);
}

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    if (!unpackFirstHitRestir(uv,params,posWS,rayDir, mat))
        return;

    neighborCount = getNeighborCount();
    M = 1;

    // preinitialize current pixel
    neighborPixelCoords[0] = uvec2(imageCoord);
    neighborShadeParams[0] = params;
    neighborPosWSs[0] = posWS;
    neighborRayDirs[0] = rayDir;
    neighborMaterials[0] = mat;

    uint bufferReadIndex = getBufferReadIndex(); 
    uint bufferWriteIndex = getBufferWriteIndex(); 

    Reservoir outReservoir = makeEmptyReservoir();

    uint acceptedSampleIndex = 0;
    float acceptedPhat = 0.0f;

    gatherNeighbors(imageCoord, imageSize,seed);

    float misWeight = M > 0 ? 1.0f / float(M) : 1.0f;
    for (uint i = 0; i < M; ++i) {

        // get this pixel's reservoir and sample (canonical sample for this pixel) 
        uint bufferReadPosition = flatten2DCoord(neighborPixelCoords[i], uvec2(imageSize));
        Reservoir reservoir_i = reservoirBuffers[bufferReadIndex].reservoirs[bufferReadPosition];
        CandidateSample sample_i = reservoir_i.bestSample;

        // calculate the p_hat of the canonical sample
        float p_hat_c = evalPhatVis(sample_i, params, posWS, rayDir, mat.materialType);

        // compute the pairwise MIS weight for neighbor resampling
        misWeight = calculatePairwiseMIS(i, sample_i, p_hat_c);

        bool positionSample = false;
        float _ = unpackMisWeight(sample_i.misWeight,positionSample);

        // the jacobian determinant needs to be calculated to scale the solid angle weight of sample_i as if it came from this pixel
        float jacobian = positionSample ? calculateJacobian(sample_i, posWS, neighborPosWSs[i]) : 1.0f;

        // calculate final resampling weight
        float w = misWeight * p_hat_c * reservoir_i.W * jacobian;

        // update the accepted index if this sample is accepted 
        if (addSample(outReservoir, sample_i, w, seed)){
            acceptedSampleIndex = i;
            acceptedPhat = p_hat_c;
        }
    }

    vec3 omega_i = outReservoir.bestSample.omega_i;
    
    bool isPosition = false;
    float _ = unpackMisWeight(outReservoir.bestSample.misWeight, isPosition);

    acceptedPhat = sanitize(acceptedPhat);

    // finalize resampling
    outReservoir.wSum = sanitize(outReservoir.wSum);
    
    outReservoir.W = sanitize(outReservoir.wSum / acceptedPhat);    

    // write output reservoir to buffer 
    uint bufferWritePosition = flatten2DCoord(gl_LaunchIDEXT.xy, uvec2(imageSize)); 
    reservoirBuffers[bufferWriteIndex].reservoirs[bufferWritePosition] = outReservoir;
}

#undef RAYGEN
