#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable
#include "common.glsl"
#include "pcs_gbuffer_shade.glsl"

layout(set = 0, binding = 4, r11f_g11f_b10f) uniform image2D outputImage;

//layout(location = 0) rayPayloadEXT HitPayload payload;


//  all zero normals are invalid
bool isGeometryValid(vec3 normal){
    float epsilon = 1e-6;
    return any(greaterThan(abs(normal),vec3(epsilon)));
}


vec3 reconstructPositionWS(vec2 uv, float depth){
    uv.y = 1.0 - uv.y;
    vec2 ndcXY = uv * 2.0 - 1.0; // move from [0, 1] to [-1, 1] range   
    vec4 camRay = cameraUBO.matInvVP * vec4(ndcXY,depth,1);
    return camRay.xyz / camRay.w;
}

float linearizeDepth(float depth, float zNear, float zFar){
    return zNear * zFar / (zFar + depth * (zNear - zFar));
}

void main()
{
   /*  traceRayEXT(
        topLevelAS,
        gl_RayFlagsOpaqueEXT,
        0xff, // cullMask
        0,    // sbtRecordOffset
        0,    // sbtRecordStride
        0,    // missIndex
        origin.xyz,
        0.001,
        direction.xyz,
        10000.0,
        0     // payloadLocation
    );*/
    
    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy);
    vec2 halfPixelOffset = 1.0 / imageSize * 0.5; 
    // without this offset the render is slightly warped compared to the rasterizer output
    vec2 uv = imageCoord / imageSize + halfPixelOffset;


    //  early exit if there's no geometry
    //  skybox is already present in outputImage (rasterizer step), so just return
    vec4 normalShininess = texture(textures[pcs.normalMapHandle], uv);
    if (!isGeometryValid(normalShininess.xyz))
        return;


    //  load the rest of the textures
    vec3 normal = normalize(normalShininess.xyz);
    float shininess = normalShininess.w;

    vec3 albedo = texture(textures[pcs.albedoMapHandle], uv).xyz;
    float depth = texture(textures[pcs.depthMapHandle], uv).x;

    vec3 posWS = reconstructPositionWS(uv,depth);
    float linDepth = linearizeDepth(depth, cameraUBO.zNear, cameraUBO.zFar) * 0.125;

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(vec3((uv),0.0), 1.0));
    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(vec3((linDepth)), 1.0));
    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(vec3((posWS)), 1.0));
}
