#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable

#include "common.glsl"
#include "math_constants.glsl"
#include "rt/pcs_raygen.glsl"
#include "raycommon.glsl"
#include "sampling.glsl"

layout(set = 0, binding = 4, r11f_g11f_b10f) uniform image2D outputImage;

layout(location = 0) rayPayloadEXT HitPayload payload;


//  all zero normals are invalid
bool isGeometryValid(vec3 normal){
    float epsilon = 1e-6;
    return any(greaterThan(abs(normal),vec3(epsilon)));
}


vec3 reconstructPositionWS(vec2 uv, float depth){
    uv.y = 1.0 - uv.y;
    vec2 ndcXY = uv * 2.0 - 1.0; // move from [0, 1] to [-1, 1] range   
    vec4 camRay = cameraUBO.matInvVP * vec4(ndcXY,depth,1);
    return camRay.xyz / camRay.w;
}

float linearizeDepth(float depth, float zNear, float zFar){
    return zNear * zFar / (zFar + depth * (zNear - zFar));
}

void main()
{ 
    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy);
    vec2 halfPixelOffset = 1.0 / imageSize * 0.5; 
    // without this offset the render is slightly warped compared to the rasterizer output
    vec2 uv = imageCoord / imageSize + halfPixelOffset;


    //  early exit if there's no geometry
    //  skybox is already present in outputImage (rasterizer step), so just return
    vec4 normalShininess = texture(textures[pcs.normalMapHandle], uv);
    if (!isGeometryValid(normalShininess.xyz))
        return;


    //  load the rest of the textures
    vec3 normal = normalize(normalShininess.xyz);
    float shininess = normalShininess.w;

    vec3 albedo = texture(textures[pcs.albedoMapHandle], uv).xyz;
    float depth = texture(textures[pcs.depthMapHandle], uv).x;


    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;


    vec3 posWS = reconstructPositionWS(uv,depth);
    vec3 direction = sampleHemisphereCosineWeighted(normal,seed).xyz;

    payload.hitValue = vec3(0.0);

    traceRayEXT(
        topLevelAS,
        gl_RayFlagsOpaqueEXT,
        0xff, // cullMask
        0,    // sbtRecordOffset
        0,    // sbtRecordStride
        0,    // missIndex
        posWS.xyz,
        0.001,
        direction.xyz /*vec3(0,1,0)*/,
        0.1,
        0     // payloadLocation
    );



    float seedf = float(seed) / float(uint(0xffffffff));

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(vec3((seedf)), 1.0));
    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(direction, 1.0));
    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(1.0 - payload.hitValue, 1.0));
}
