//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../raycommon.glsl"
#include "../structs/payload.glsl"

layout(set = 0, binding = 4, rgba32f) uniform image2D outputImage;

layout(location = 0) rayPayloadEXT HitPayloadNaive payload;

//  all zero normals are invalid
bool isGeometryValid(vec3 normal){
    float epsilon = 1e-6;
    return any(greaterThan(abs(normal),vec3(epsilon)));
}

vec3 reconstructPositionWS(vec2 uv, float depth){
    uv.y = 1.0 - uv.y;
    vec2 ndcXY = uv * 2.0 - 1.0; // move from [0, 1] to [-1, 1] range   
    vec4 camRay = cameraUBO.matInvVP * vec4(ndcXY,depth,1);
    return camRay.xyz / camRay.w;
}


vec3 fresnelSchlick(vec3 F_0, float cos_theta_h){
    float v = 1.0 - cos_theta_h;
    v = v * v * v * v * v; //fifth power
    return F_0 + (1.0 - F_0) * v;
}

float distrGGX(float alpha, float cos_theta_m){

    if (cos_theta_m <= 0)
        return 0.0f;

    alpha = max(alpha, 1e-3);
    cos_theta_m = clamp(cos_theta_m, 0.0f, 1.0f);

    float a2 = alpha * alpha;
    float cos_theta_m2 = cos_theta_m * cos_theta_m;

    float term = (a2 - 1.0f) * cos_theta_m2 + 1;
    float term2 = term * term;

    float denom = PI * term2;

    float res = a2 / denom; 

    if (isinf(res) || isnan(res))
        return 0.0f;

    return res;
}

float auxSmith(float cos_theta, float alpha){
    float a2 = alpha * alpha;
    float cos_theta2 = cos_theta * cos_theta;
    float term =  sqrt(1.0 + a2 * (1.0 / cos_theta2 - 1.0));

    return (term - 1.0) / 2.0;
}

float G_Smith(float cos_theta_o, float cos_theta_i, float alpha){
    float aux_theta_o = auxSmith(cos_theta_o, alpha);
    float aux_theta_i = auxSmith(cos_theta_i, alpha);

    return 1.0 / (1.0 + aux_theta_o + aux_theta_i);
}

// PBR TEST
vec3 getWeightFactorPbr(vec3 rayDir,vec3 normal, vec3 albedo, float roughness, float metallic, inout uint seed, inout vec3 outDir){
    
    vec3 omega_o = -rayDir;
    float alpha =  roughness * roughness;

    // sample GGX VNDF to obtain omega_h -- microfacet normal
    float ksi1 = rand(seed);
    float ksi2 = rand(seed);
    vec3 omega_h = normalize(SampleVndf_GGX(vec2(ksi1, ksi2), omega_o, alpha, normal));
    
    // evaluate Fresnel term first and use it to choose between a diffuse or specular sample
    float cos_theta_h = max(dot(omega_h, omega_o), 0.0f); // angle between microfacet normal and view direction

    vec3 F0 = mix(vec3(0.04), albedo, metallic);
    vec3 F = fresnelSchlick(F0, cos_theta_h);
    float FMax = max(F.x,max(F.y,F.z));

    float specProb = FMax;

    float ksi3 = rand(seed);
    bool isSpecularBounce = ksi3 < specProb;
    
    vec3 brdf = vec3(0.0);
    vec3 sampleDir = vec3(0.0);
    float pdf = 0.0;

    float pdf_spec = 0.0;
    float pdf_diff = 0.0;

    if (isSpecularBounce) {

        // evaluate omega_i (bounce direction): reflect view direction (omega_o) around the microfacet normal (omega_h)
        vec3 omega_i = reflect(rayDir, omega_h);

        if (dot(omega_i, normal) < 0.0)
            return vec3(0.0);

        float cos_theta_m = max(dot(omega_h, normal), 0.0f); // angle between microfacet normal and surface normal

        float cos_theta_o = max(dot(omega_o, normal), 0.0); // angle between view direction and surface normal
        float cos_theta_i = max(dot(omega_i, normal), 0.0); // angle between light direction and surface normal

        float NDF = distrGGX(alpha, cos_theta_m);
        float G = G_Smith(cos_theta_o, cos_theta_i, alpha); 

        brdf = NDF * G * F / (4.0f * cos_theta_o * cos_theta_i);
        
        sampleDir = omega_i;

        pdf_spec = pdf_vndf_isotropic(omega_i, omega_o, alpha, normal);
        pdf_diff = getPdfHemisphereCosineWeighted(omega_i, normal);
        pdf = pdf_spec * specProb + pdf_diff * (1.0f - specProb);
    } 
    else {

        vec4 sampled = sampleHemisphereCosineWeighted(normal, seed);

        vec3 kD = (1.0f - F0) * (1.0f - metallic);

        brdf = kD * albedo * INVPI;

        sampleDir = sampled.xyz;

        pdf_diff = sampled.w; 
        pdf_spec = pdf_vndf_isotropic(sampled.xyz, omega_o, alpha, normal);
        pdf = pdf_diff * (1.0 - specProb) + pdf_spec * specProb; 
    }
    float cos_theta_i = max(dot(sampleDir,normal), 0.0f);
    vec3 weightFactor = brdf * cos_theta_i / pdf;

    outDir = sampleDir;
    return weightFactor;
}

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    //  if there's no geometry, draw the sky into the output image and early exit (no rays traced)
    //  (in this case, the sky texture is already pre-rendered in the G buffer shading target texture) 
    vec4 normalRoughness = texture(textures[pcs.normalMapHandle], uv);
    if (!isGeometryValid(normalRoughness.xyz)){
        vec3 sky = texture(textures[pcs.targetHandle],uv).xyz;
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(sky, 1.0));
        return;
    }

    // early exit on emissive materials -- write emission directly into output image
    Material mat = materialUBO.materials[uint(texture(utextures[pcs.materialMapHandle],uv).r)];
    if (any(notEqual(mat.emissionMetallic.rgb,vec3(0.0)))){
        imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(mat.emissionMetallic.rgb, 1.0));
        return;
    }

    //  load the rest of the textures
    vec3 normal = normalize(normalRoughness.xyz);
    float roughness = normalRoughness.w;

    vec4 albedoMetallic = texture(textures[pcs.albedoMapHandle], uv);
    vec3 albedo = albedoMetallic.rgb;
    float metallic = albedoMetallic.w;

    float depth = texture(textures[pcs.depthMapHandle], uv).x;

    // initial ray and shading parameters
    // at first, take them from the G buffer fill step, then reuse them when bouncing rays  
    vec3 posWS = reconstructPositionWS(uv,depth);
    vec3 rayDir = normalize(posWS - cameraUBO.posWS);

    vec4 sampled = sampleMaterial(normal, rayDir, mat.materialType, seed);
    vec3 direction = sampled.xyz;
    float pdf = sampled.w;
    float cosThetaI = mat.materialType == 1 ? 1.0 : max(dot(direction,normal),0.0);
    vec3 brdf = mat.materialType == 1 ? albedo : albedo * INVPI;
    vec3 weightFactor = brdf * cosThetaI / pdf;

    float tMin = 0.001f;
    float tMax = 10000.0f;

    vec3 radiance = vec3(0.0);
    vec3 weight = vec3(1.0);

    if (mat.materialType == 2)
        weightFactor = getWeightFactorPbr(rayDir, normal, albedo, roughness,metallic, seed, direction);


    resetPayload(payload);
    bool lastWasMirror = mat.materialType == 1;
    for (uint depth = 0; depth < pcs.maxRecursionDepth; depth++){

        resetPayload(payload);
        payload.seed = seed;
        traceRayEXT(
            topLevelAS,
            gl_RayFlagsOpaqueEXT,
            0xff, // cullMask
            0,    // sbtRecordOffset
            0,    // sbtRecordStride
            0,    // missIndex
            posWS + tMin * normal,
            tMin,
            direction,
            tMax,
            0     // payloadLocation
        );

        weight *= weightFactor;
        radiance += weight * payload.hitEmission;  

        if(!payload.hit) 
            break;

        ///////////////////////////////////////////////////////////
        // russian roulette termination
        // use troughput as weight to set survival probability
        // activate only at depth > 4 to avoid premature termination of paths and potential energy loss
        if (depth > 4) {
            float survivalProb = max(weight.x,max(weight.y,weight.z));
            survivalProb = max(survivalProb, 0.15);
            float rnd = rand(seed);
            if (rnd > survivalProb) break;
            weight /= survivalProb;
        }
        ///////////////////////////////////////////////////////////

        posWS = payload.hitPosition;
        direction = payload.nextSample.xyz;
        pdf = payload.nextSample.w;
        weightFactor = payload.weightFactor;
        seed = payload.seed;
        normal = payload.hitNormal;
    }

    if (pcs.accumulate == 1){
        vec3 oldRadiance = imageLoad(outputImage, ivec2(gl_LaunchIDEXT.xy)).xyz;
        radiance = mix(oldRadiance,radiance, 1.0f / float(pcs.frameCtr + 1));
    }

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(radiance, 1.0));
}