//https://github.com/yknishidate/single-file-vulkan-pathtracing
//https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_query : require

#define RAYGEN


#include "../../common/common.glsl"
#include "../../common/math_constants.glsl"
#include "../pcs/pcs_raygen.glsl"
#include "../raycommon.glsl"
#include "../payload.glsl"

layout(location = 0) rayPayloadEXT HitPayloadNaive payload;

void main() { 

    // Calc seed
    uvec2 s = pcg2d(ivec2(gl_LaunchIDEXT.xy) * (pcs.seed));
    uint seed = s.x + s.y;

    //  calculate texture coordinate for sampling
    vec2 imageSize = vec2(imageSize(outputImage));
    vec2 imageCoord = vec2(gl_LaunchIDEXT.xy) + 0.5; // add half pixel offset (sample pixel centers, not corners)
    vec2 uv = imageCoord / imageSize;

    ShadeParams params;
    vec3 posWS;
    vec3 rayDir;
    Material mat;

    if (!unpackFirstHit(uv,params,posWS,rayDir, mat))
        return;

    vec3 brdf = vec3(0.0);
    vec4 sampled = sampleMaterial(rayDir, params,mat.materialType, seed, brdf);
    vec3 direction = sampled.xyz;
    float pdf = sampled.w;

    float cosThetaI = mat.materialType == MAT_MIRROR ? 1.0 : max(dot(direction,params.normal),0.0);

    vec3 weightFactor = vec3(0.0);
    if (pdf > 0.0f)
        weightFactor = brdf * cosThetaI / pdf;

    float tMin = 0.001f;
    float tMax = 10000.0f;

    vec3 radiance = vec3(0.0);
    vec3 weight = vec3(1.0);

    resetPayload(payload);

    for (uint depth = 0; depth < pcs.maxRecursionDepth; depth++){

        resetPayload(payload);
        payload.seed = seed;
        traceRayEXT(
            topLevelAS,
            gl_RayFlagsOpaqueEXT,
            0xff, // cullMask
            0,    // sbtRecordOffset
            0,    // sbtRecordStride
            0,    // missIndex
            posWS + tMin * params.normal,
            tMin,
            direction,
            tMax,
            0     // payloadLocation
        );

        weight *= weightFactor;
        radiance += weight * payload.hitEmission;  

        if(!payload.hit) 
            break;

        ///////////////////////////////////////////////////////////
        // russian roulette termination
        // use troughput as weight to set survival probability
        // activate only at depth > 4 to avoid premature termination of paths and potential energy loss
        if (depth > 4) {
            float survivalProb = max(weight.x,max(weight.y,weight.z));
            survivalProb = max(survivalProb, 0.15);
            float rnd = rand(seed);
            if (rnd > survivalProb) break;
            weight /= survivalProb;
        }
        ///////////////////////////////////////////////////////////

        posWS = payload.hitPosition;
        direction = payload.nextSample.xyz;
        pdf = payload.nextSample.w;
        weightFactor = payload.weightFactor;
        seed = payload.seed;
        params.normal = payload.hitNormal;
    }

    if (pcs.accumulate == 1){
        vec3 oldRadiance = imageLoad(outputImage, ivec2(gl_LaunchIDEXT.xy)).xyz;
        radiance = mix(oldRadiance,radiance, 1.0f / float(pcs.frameCtr + 1));
    }

    imageStore(outputImage, ivec2(gl_LaunchIDEXT.xy), vec4(radiance, 1.0));
}


#undef RAYGEN
